### ISSUE TITLE
Determine keys

### ISSUE THREAD

**Issue by macsyd** [macsyd/csc370-database-project#16]
Determine functional dependencies and keys and superkeys for each relation (table) in the database.

**Comment by jacobarychuk** [comment]
I know that @Leonard-Barnes worked on this last sprint. I will review it and then we can work on the next tasks that depend on this being done.

**Comment by jacobarychuk** [comment]
Done. I also added some notes about the theory in keys_superkeys.md on the sprint-2-sql branch.
