### ISSUE TITLE
Put DB in BCNF

### ISSUE THREAD

**Issue by macsyd** [macsyd/csc370-database-project#17]
Investigate whether our database is in BCNF by checking for BCNF violations and making changes as needed. Will need to know keys/superkeys (and functional deps) to do this

**Comment by jacobarychuk** [comment]
I will start on this while I review the lecture material. Anyone else is welcome to work on it too; just assign yourself.

**Comment by jacobarychuk** [comment]
Looks like no changes needed. I wrote some notes about it on the linked branch (sprint-2-sql).
