### ISSUE TITLE
Add and test foreign key constraints

### ISSUE THREAD

**Issue by macsyd** [macsyd/csc370-database-project#18]
- Add foreign key constraints to our database
- Attempt to create data anomalies and observe how well our database prevents them from occurring (success criteria is 100% of attempted data anomalies rejected)
- Should probably do this after the DB is in BCNF

**Comment by jacobarychuk** [comment]
I think @Leonard-Barnes worked on foreigns keys during last sprint, so I will review that first. Then, I'll write some queries that attempt to create data anomalies. Anyone else is welcome to help with this; just assign yourself.

**Comment by jacobarychuk** [comment]
The foreign key constraints look good. I wrote many queries to test the foreign key constraints, all of which the database rejects. This is now done.
