### ISSUE TITLE
Add and test example user privileges

### ISSUE THREAD

**Issue by macsyd** [macsyd/csc370-database-project#28]
- Add example users to our database and manage their access by giving them specific privileges.
- Attempt to run queries that the user does not have privileges for and observe how our database prevents this from happening (success criteria is 100% of these queries should fail).

**Comment by jacobarychuk** [comment]
I added 6 example users (3 employees, 3 admins) to the database and assigned them privileges. Then, I wrote queries to demonstrate some of the things they can and cannot do. I only wrote one query so far that demonstrates what they cannot do, which failed (so far meeting the success criteria).

**Comment by jacobarychuk** [comment]
I do not have time to write any more queries that the user does not have privileges for.
