### ISSUE TITLE
Data Consistency - test violation handling

### ISSUE THREAD

**Issue by macsyd** [macsyd/csc370-database-project#31]
Competency: "Enforces consistency: Enforces consistency with check constraints and assertions"

Enforce consistency on our database and attempt to run queries that violate our schema to observe how well our database handles this (success criteria is 100% of these queries should fail).

**Comment by jacobarychuk** [comment]
I can spent a little bit of time on this later today, unless someone else beats me to it (which is fine).

**Comment by jacobarychuk** [comment]
I identified the parts of our schema that enable data inconsistencies, but these will have to be fixed next sprint.
