### ISSUE TITLE
Enforce consistency

### ISSUE THREAD

**Issue by jacobarychuk** [macsyd/csc370-database-project#43]
- Enforce consistency on our database by not allowing the inconsistencies we discovered this sprint to be added to the database. We will measure this using queries that violate our schema which we wrote this sprint (success criteria is 100% of these queries should fail)

**Comment by jacobarychuk** [comment]
I added NOT NULL constraints, which addressed all but one of the inconsistencies identified last sprint. Now, 11/12 of the queries correctly fail. The last one (about the timestamps) will probably require a trigger, which is not in scope for this sprint.

**Comment by macsyd** [comment]
The timestamps constraint (CreationDate should be less than ExpiryDate - are there others?) can be implemented with a check constraint which adds a constraint to each tuple (checks that condition is satisfied every time data is updated) and should be pretty simple - I think we can implement it this sprint. Although I guess that is technically part of advanced SQL so we could leave for another sprint if you want

**Comment by jacobarychuk** [comment]
Yes, the constraint that CreationDate should be less than ExpiryDate is the only missing constraint related to the timestamps that I know of. We can just implement it now so that we can say all the inconsistencies are fixed and be done with it. I guess using check constraints to enforce consistency was a module-level competency from way back in the ACID Transactions module, so arguably we are not jumping ahead by doing it now.

**Comment by jacobarychuk** [comment]
I added the check constraint and now we have 100% of queries correctly fail.
