### ISSUE TITLE
Simplify sub queries

### ISSUE THREAD

**Issue by macsyd** [macsyd/csc370-database-project#50]
Competency: "Simplifies queries: Simplifies a complex query by converting a sub-query into a (outer?) join"

- If possible, simplify our earlier queries (in [DemoQueries.sql](https://github.com/macsyd/csc370-database-project/blob/main/project-deliverables/sprint-4/project-deliverables/sprint-2/DemoQueries.sql)) that used sub-queries by potentially converting them into a join

**Comment by jacobarychuk** [comment]
I started on this by simplifying our three subqueries in [DemoQueries.sql](https://github.com/macsyd/csc370-database-project/blob/main/project-deliverables/sprint-2/DemoQueries.sql). I wrote the simplified versions in [SimplifiedSubqueries.sql](https://github.com/macsyd/csc370-database-project/blob/sprint-5/project-deliverables/sprint-5/SimplifiedSubqueries.sql).
